#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -yoffset -75 -xoffset -69 -width 15 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "Fantasque Sans Mono Nerd 12" <<< "Lock|Logout|Reboot|Shutdown")"
            case "$MENU" in
                *Lock) light-locker-command -l ;;
                *Logout) i3-msg exitt ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
