tap 'argoproj/tap'

brew 'ansible'
brew 'argocd'
brew 'autossh'
brew 'awscli'
brew 'cairo'
brew 'checkov'
brew 'curl'
brew 'direnv'
brew 'gh'
brew 'git'
brew 'go'
brew 'helm'
brew 'kind'
brew 'kubeconform'
brew 'kubernetes-cli'
brew 'minikube'
brew 'nkf'
brew 'nodebrew'
brew 'openldap'
brew 'openssl@1.1'
brew 'peco'
brew 'perl'
brew 'pre-commit'
brew 'pyenv'
brew 'python@3.9'
brew 'rbenv-communal-gems'
brew 'rbenv'
brew 'ruby-build'
brew 'ruby'
brew 'sqlite'
brew 'tfenv'
brew 'tree'
brew 'wget'
brew 'zsh'

# cask 'alfred'                 # -> raycast
# cask 'clipy'                  # -> raycast
# cask 'google-japanese-ime'    # -> manual install
# cask 'iterm2'                 # -> warp
cask 'docker'
cask 'google-chrome'
cask 'karabiner-elements'
cask 'raycast'
cask 'visual-studio-code'
cask 'warp'
